name: Deploy DEV

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terrform.yml
    with:
      environment: dev
      aws-assume-role-arn: arn:aws:iam::<ACCOUNT_ID>:role/github-actions-deploy-role-axcloud
      aws-region: sa-east-1
      aws-statefile-bucket: axcloud-lab-sa-east-1-terraform-state
      aws-lock-athena-table: axcloud_lab_terraform_locks

    env:
      S3_BUCKET: axcloud-lab-sa-east-1-data
      LAMBDA_NAME: axcloud-lab-lambda-ingest
      GLUE_JOB_NAME: axcloud-lab-glue-shell-athena-exec
      SNS_TOPIC_ARN: arn:aws:sns:sa-east-1:<ACCOUNT_ID>:axcloud-lab-topic-ingest
      SQL_S3_KEY: sql/dml/insert_curated_messages.sql
      GLUE_SCRIPT_S3_KEY: glue/python_shell/runner.py

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Package Lambda
        run: |
          cd src/lambda_ingest
          zip -r ../../lambda.zip . -x "*__pycache__*" "*.pytest_cache*"
          ls -lh ../../lambda.zip

      - name: Upload Athena DML to S3
        run: |
          aws s3 cp "athena/dml/insert_curated_messages.sql" "s3://${S3_BUCKET}/${SQL_S3_KEY}"

      - name: Upload Glue script to S3
        run: |
          aws s3 cp "glue/python_shell/runner.py" "s3://${S3_BUCKET}/${GLUE_SCRIPT_S3_KEY}"

      - name: Deploy Lambda code
        run: |
          aws lambda update-function-code \
            --function-name "${LAMBDA_NAME}" \
            --zip-file "fileb://lambda.zip"

      - name: Update Glue Job script location
        run: |
          aws glue update-job \
            --job-name "${GLUE_JOB_NAME}" \
            --job-update "Command={Name=pythonshell,ScriptLocation=s3://${S3_BUCKET}/${GLUE_SCRIPT_S3_KEY}}"

      - name: Smoke test - publish SNS message
        run: |
          aws sns publish \
            --topic-arn "${SNS_TOPIC_ARN}" \
            --message "{\"hello\":\"world\",\"from\":\"github-actions-dev\"}"